### ISSUE TITLE
can't center contact page

### ISSUE THREAD

**Issue by kas** [kenschnall/behrend-lion-ambassadors#3]

**Comment by malindamiller** [comment]
I centered it.  I want to implement a bootstrap form to make it look really nice but haven't figured it out yet/

**Comment by kas** [comment]
Okay it looks fine now.  I am not sure how to get that but I have been looking at foundation http://foundation.zurb.com/ so I can try to set that up if you have the backend all set up

**Comment by kas** [comment]
Looks good!
