### ISSUE TITLE
Instagram Logo floating

### ISSUE THREAD

**Issue by malindamiller** [kenschnall/behrend-lion-ambassadors#6]
The Instagram logo is floating off the menu bar.

**Comment by kas** [comment]
This is what I see after pulling your updates and bundle installing and running a db:migrate command

http://imgur.com/4d7xaPb

We can modify the code on your laptop during/after the meeting tomorrow, I think I know the problem and we just need to subtract .05 px in a css element to get it back in line on your computer

**Comment by kas** [comment]
Fixed in #14
